### PR TITLE
add new maintainer

### PR DESCRIPTION
**Pull request by rluria14**
Checklist
    * [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
    * [x] Bumped the build number (if the version is unchanged)
    * [x] Reset the build number to `0` (if the version changed)
    * [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
    * [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dbast** [comment]
Hi @rluria14 why do you want to add yourself to multiple R feedstocks? You can just propose updates to any feedstock via PR already ... as part of an update you can then also propose yourself as maintainer.

**Comment by rluria14** [comment]
@dbast the new maintainer added is a group github account that my team uses to track all of the feedstocks we maintain

**Comment by dbast** [comment]
@rluria14 You can press the watch button of the repo for tracking also

**Comment by jdblischak** [comment]
Also I don't think it is necessary to bump the version number. That triggers a new build of the conda binary that gets uploaded to Anaconda Cloud. Adding a maintainer is handled by the linter script, so I don't think it requires building a new binary (please let me know if I am mistaken).

**Pull request merged**
